// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/data": {
            "put": {
                "description": "Принимает JSON пакет от AIS, ставит в очередь на отправку в 1С.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integration"
                ],
                "summary": "Прием данных (Sale/Update/Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Пакет данных",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AISRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Принимает JSON пакет от AIS, ставит в очередь на отправку в 1С.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integration"
                ],
                "summary": "Прием данных (Sale/Update/Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Пакет данных",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AISRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Принимает JSON пакет от AIS, ставит в очередь на отправку в 1С.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Integration"
                ],
                "summary": "Прием данных (Sale/Update/Delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Пакет данных",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AISRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AISDocument": {
            "type": "object",
            "properties": {
                "ClientActualAddress": {
                    "type": "string"
                },
                "ClientCity": {
                    "type": "string"
                },
                "ClientClientTypeId": {
                    "type": "string"
                },
                "ClientContractorTypeId": {
                    "type": "string"
                },
                "ClientEmail": {
                    "type": "string"
                },
                "ClientFieldOfActivity": {
                    "type": "string"
                },
                "ClientFullName": {
                    "type": "string"
                },
                "ClientId": {
                    "description": "--- Client Fields ---",
                    "type": "string"
                },
                "ClientIndex": {
                    "type": "string"
                },
                "ClientLeaderDuty": {
                    "type": "string"
                },
                "ClientLeaderFullName": {
                    "type": "string"
                },
                "ClientLegalAddress": {
                    "type": "string"
                },
                "ClientPhone": {
                    "type": "string"
                },
                "ClientVOENOrPassportNo": {
                    "type": "string"
                },
                "ClientWebsite": {
                    "type": "string"
                },
                "ContractEndDate": {
                    "type": "string"
                },
                "ContractId": {
                    "description": "--- Contract Fields ---",
                    "type": "string"
                },
                "ContractIsTransfer": {
                    "type": "boolean"
                },
                "ContractNo": {
                    "type": "string"
                },
                "ContractPayTime": {
                    "type": "string"
                },
                "ContractSignedDate": {
                    "type": "string"
                },
                "ContractStartDate": {
                    "type": "string"
                },
                "ContractStatus": {
                    "type": "string"
                },
                "ContractType": {
                    "type": "string"
                },
                "DepartmentName": {
                    "type": "string"
                },
                "PayStatusName": {
                    "type": "string"
                },
                "PrecinctName": {
                    "description": "--- Reference Fields ---",
                    "type": "string"
                },
                "Privilege": {
                    "type": "string"
                },
                "SaleCarNumber": {
                    "type": "string"
                },
                "SaleClientId": {
                    "type": "string"
                },
                "SaleComment": {
                    "type": "string"
                },
                "SaleDate": {
                    "type": "string"
                },
                "SaleDeclarationNo": {
                    "type": "string"
                },
                "SaleDetails": {
                    "description": "--- Array of Nomenclatures ---",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SaleDetail"
                    }
                },
                "SaleId": {
                    "description": "--- Sale Fields ---",
                    "type": "string"
                },
                "SaleInspectorId": {
                    "type": "string"
                },
                "SaleIsDiplomatic": {
                    "type": "boolean"
                },
                "SaleMainAmount": {
                    "type": "number"
                },
                "SalePayDate": {
                    "type": "string"
                },
                "SalePayStatusId": {
                    "type": "string"
                },
                "SalePayType": {
                    "type": "string"
                },
                "SalePaymentType": {
                    "type": "string"
                },
                "SalePrecinctId": {
                    "type": "string"
                },
                "SaleVatAmount": {
                    "type": "number"
                },
                "TransactionAmount": {
                    "type": "number"
                },
                "TransactionBalanceBeforeSale": {
                    "type": "number"
                },
                "TransactionComment": {
                    "type": "string"
                },
                "TransactionDate": {
                    "type": "string"
                },
                "TransactionId": {
                    "description": "--- Transaction Fields ---",
                    "type": "string"
                },
                "TransactionIsSale": {
                    "type": "boolean"
                },
                "UserActive": {
                    "type": "boolean"
                },
                "UserEmail": {
                    "type": "string"
                },
                "UserFirstName": {
                    "type": "string"
                },
                "UserId": {
                    "description": "--- User Fields ---",
                    "type": "string"
                },
                "UserLastName": {
                    "type": "string"
                },
                "UserName": {
                    "type": "string"
                },
                "UserPhone": {
                    "type": "string"
                },
                "UserPrecinctId": {
                    "type": "string"
                },
                "UserRegistrationDate": {
                    "type": "string"
                },
                "UserStatusId": {
                    "type": "string"
                }
            }
        },
        "models.AISRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Основные данные документа",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AISDocument"
                        }
                    ]
                },
                "id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "description": "Тип документа: \"sale\", \"return\" и т.д.",
                    "type": "string"
                }
            }
        },
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.SaleDetail": {
            "type": "object",
            "properties": {
                "SaleDetailAmount": {
                    "type": "number"
                },
                "SaleDetailId": {
                    "type": "string"
                },
                "SaleDetailPrice": {
                    "type": "number"
                },
                "SaleDetailQuantity": {
                    "type": "number"
                },
                "SaleDetailSaleId": {
                    "type": "string"
                },
                "SaleDetailServiceId": {
                    "type": "string"
                },
                "SaleDetailTotalAmount": {
                    "type": "number"
                },
                "SaleDetailVATAmount": {
                    "type": "number"
                },
                "SaleDetailVATRate": {
                    "type": "number"
                },
                "ServiceCode": {
                    "type": "string"
                },
                "ServiceName": {
                    "description": "Дополнительные поля по услуге",
                    "type": "string"
                },
                "ServiceUnit": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "AIS-1C Proxy API",
	Description:      "Сервис интеграции AIS и 1С. Гарантированная доставка сообщений через очередь.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
